extends Node

signal move_selected(tile: BoardTile)
signal moved(tile: BoardTile)
signal mouse_over(tile: BoardTile)
signal place_summon(tile: BoardTile)
signal current_power_changed(power: int)
signal max_power_changed(power: int)
signal turn_complete()
signal invalid_move()
signal summon_placed()
signal selected_element_type_changed(element_type: Element.Type)
signal enemy_move(enemy: Enemy, tile: BoardTile)
signal enemy_place_summon(enemy: Enemy, tile: BoardTile, element_type: Element.Type)
signal enemy_power_changed(enemy: Enemy, power: int)
signal enemy_killed(enemy: Enemy)
signal floor_cleared(floor: int)
signal enemy_cant_move(enemy: Enemy)
signal change_game_state(state: Game.GameState)
signal game_over()
